[env:esp32_wroom]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/RTClib @ ^2.1.3
    LiquidCrystal_I2C @ ^1.1.4
    arduino-libraries/Servo @ ^1.2.1
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0

[env:esp32_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; CDC settings: prevent USB-UART from resetting on DTR/RTS changes
; This keeps the serial terminal connected during hard resets
monitor_rts = 0
monitor_dtr = 0
lib_deps =
    adafruit/RTClib @ ^2.1.3
    LiquidCrystal_I2C @ ^1.1.4
    arduino-libraries/Servo @ ^1.2.1
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    adafruit/RTClib @ ^2.1.3
    LiquidCrystal_I2C @ ^1.1.4
    arduino-libraries/Servo @ ^1.2.1
